//WAP BMI IS A MEASURE OF HEALTH ON WEIGHT IT CAN BE CALCULATED BY TAKING UR WEIGHT IN KG AND DIVIDING BY THE SQUARE OF UR HEIGHT IN METERS 
//WAP THAT PROMPT THE USER TO ENTER A WEIGHT IN POUNDS AND HEIGHT IN INCHIES AND DISPLAY BMI 
//1 POUND = 0.45 KG
//1 INCH = 0.0254 M